{% set name = "cchardet" %}
{% set version = "1.1.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "b4ccd55b0e917d98fa94aee19b7551e9d38d0835b608ebe843f72b48587e6b74" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain

  run:
    - python

test:
  imports:
    - cchardet

about:
  home: https://github.com/PyYoshi/cChardet
  license_file: {{ RECIPE_DIR }}/COPYING
  license: MPL 1.1
  license_family: OTHER
  summary: 'cChardet is high speed universal character encoding detector.'
  dev_url: https://github.com/PyYoshi/cChardet
  doc_url: https://github.com/PyYoshi/cChardet

extra:
  recipe-maintainers:
    - pmlandwehr
