# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YUeLdXjU3+v0THQntIb2vQEBy+e0hVyPlBV/GUjcD7ZR/NUsfYhfohx0b4LJI0VeyqjzO6ls/sTr0C4ACvzRmJbh1bRz0XsHwvXTnAXD8jmG6zDPyiwVxsXk7GE+GKmLHLE9Y+SfA9M30Nphlo3y53D5qO6LxF/0k6KZrRw+jb1cJhw1MEZYQOpycd3k1MmH3U6iTYUS1YJhNXwxi8xMO+b7KjxxL6U50ATiVLTtrCWew4jPOj+z6JxdxregPZnZw/IKVmuqk2Y6u1CgBScVllovuJDn1wWwgzOt/GeKdj+t8m/FRpgmRCXFIOGgL7NOGjj9tbJcNS0KgvyVydEpjYB7H/YLLTR5bZOpTB2mzKYZzI/dJ1uEjTe+z+iPo5zduu98UGwQES5elfRQvO77STBdlaSmqIPGuctTdetK0WB63poM19Oy6A6HaIDBue7163u7BAx+q652XpwNrIullJK/krfe6GpnWS73iugE3fwlnYDDCEq8+3a9DKfpyzPmhPthnyGJTBPmN0VUCy32/Cn0234lFRLIXRbtGCFftdarB6EUhmkTwvgMiG+8TBuBVL+cb+ca3KyTAQR9loCZ64hebjB3r6WkGm1aqeUxw7eYZqooH8JQ2NAhe9Jj5r38gpsskkXInvq6GSpKN7c0DHFH2Gv2CjvQX2ohNFZcx7Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
