travis:
  secure:
    BINSTAR_TOKEN: Vg5RybVCX9uOQ5hKf+tNmadWWPvpaqu8TrhOBVLGr4Nv1iJTr/D7GAqUhc2RWnzULMFG+yyIAWtev2hKJ2A5SmSBvCxYPynLQFl5I092/UFcio6/7P58qxV2B885F79W4vFf1FGEfpvWMjxW7SCkV2L7Hyf0iIMmJlMd22NLJ0fTiYddfd7PQL2LgcldpPV3H9pIl7S8zBaCCdW0oUByp8h2OzTinQBmtReeze/x2maQwgabR7RlvNETtPnKM3lb9P8dgwowbk2p59B+k6XX3hWM0SrCiL2hkj9mtp/MJtUE8q20f74wrxW00JfsoXTkKZABgyMyuEB2yUQ3Z4iMqaNdtBLkJK4hkJ7dG0HW+LEOUWgIRxjZqZ+8VvE7lPYvDM3ggx1fGeIj+hJ2s45knLMPw2WI0FDRwY4h1p2uSpA5q9r5Nm4RvefYUzvbf48xxQOQ5nBm9BowfO7FIVtGzqmELB9xtKmPjUfj9qhn+62D1MNxb98o4EYpWL/omSxOul/D/3T3wD2HTrJOE+t0ocw97vLGyRkLv3cl6rMrDdqVhnRkQMQZMJyL/IQwj12Si2zzMdrbW+myQDyd8CL2j34eri6skHMQIQDYsniprpsUZIodwijR5hFHojoYljQlcilyvlvZOQNhGx6nTkWAjfz+b2Cvo/ynwMeYRrWZ4FM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
